config/routes.rb
Rails.application.routes.draw do

root "homes#index"
resources :students
  
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
    validates :first_name, :last_name, :email, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def index
      @students = Student.all
      render json: { student: @students}
    end

    def new
      @student = Student.new
    end

    
     def create
       @student = Student.new(student_params)
        if @student.save
        redirect_to students_path
       else
        render :new
      end
     end
  
  def show 
    @student = Student.find(params[:id])
  end

  def edit 
    @student = Student.find(params[:id])
  end 

  def update
    @student = Student.find(params[:id])
   if @student.update(student_params)
      redirect_to students_path 
    else
      render :edit
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    redirect_to students_path
  end

  private 
  def student_params 
    params.require(:student).permit(:first_name, :last_name, :email
    )
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/index.html.erb
<button type="button" class="btn btn-primary" id="yogi" data-bs-toggle="modal" data-bs-target="#exampleModal">
  All Student record Open
</button>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Popup Title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="studentsTableBody">
        <p>This is the content of the popup. Customize it as needed.</p>
      </div>
      <div class="modal-footer">  
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<script>
    $(document).ready(function () {
        $('#yogi').click(function () {
            $.ajax({
                method: 'GET',
                url: 'students',
                dataType: 'json',
                success: function (data) {
        
          $('#studentsTableBody').empty();

         
          $.each(data.student, function (index, student) {
            $('#studentsTableBody').append(
              '<tr>' +
                '<td>' + student.id + '</td>' +
                '<td>' + student.first_name + '</td>' +
                '<td>' + student.last_name + '</td>' +
                '<td>' + student.email + '</td>' +
                '</tr>'
            );
          });
        },errors: function (xhr, status, error) {
                    console.log(error);
                },
            });
        });
    });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apsimpact</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<h1>Edit Student</h1>

<%= form_with model: @student do |form|%>

<% if @student.errors.any? %>
 <% @student.errors.full_messages.each do |message|%>
 <p><%= message %></p>
 <%end%> 
<%end%>


<div>
    <%=form.label :first_name%>
    <%=form.text_field :first_name%>
</div><br>

<div>
   <%=form.label :last_name%>
   <%=form.text_field :last_name%>
</div><br>

<div>
   <%=form.label :email%>
   <%=form.email_field :email%>
</div><br> 


<div>
    <%= form.submit "Save "%>
</div>

<%end%>

app/views/students/index.html.erb
<h1>All Student List</h1>
<%=link_to "New Student", new_student_path %>
<table > 
    <thead  class="spacing">
        <tr>
            <th>First-name</th>
            <th>last-name</th>
            <th>Email</th>
            <th>Action</th> 


        </tr>
    </thead>
    <tbody>
        <% @students.each do |student|%>
        <tr>
            <td><%= student.first_name%></td>
            <td><%= student.last_name%></td>
            <td><%= student.email%></td>
            <td><%= link_to "view",student %></td>
            <td><%= link_to "edit",edit_student_path(student) %></td>
           <td><%= button_to "delete", student, :method => :delete %></td>

           </tr>
        <%end%>
    </tbody> 
</table> 

app/views/students/new.html.erb
<h1>New Student</h1>

<%= form_with model: @student do |form|%>

<% if @student.errors.any? %>
 <% @student.errors.full_messages.each do |message|%>
 <p><%= message %></p>
 <%end%> 
<%end%>


<div>
    <%=form.label :first_name%>
    <%=form.text_field :first_name%>
</div><br>

<div>
   <%=form.label :last_name%>
   <%=form.text_field :last_name%>
</div><br>

<div>
   <%=form.label :email%>
   <%=form.email_field :email%>
</div><br> 


<div>
    <%= form.submit "create student"%>
</div>

<%end%>

app/views/students/show.html.erb
<h1>Student Details</h1>

<p><strong>First Name:</strong> <%= @student.first_name %></p>
<p><strong>Last Name:</strong> <%= @student.last_name %></p>
<p><strong>Email:</strong> <%= @student.email %></p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path(@student)  %>